config/routes.rb
Workspace::Application.routes.draw do
  
  resources :users
  get "sign_up" => "users#new"
  get "about" => 'static_pages#about'
  get "contact" => 'static_pages#contact'
  get "static_pages/home"
  get "sign_in" => 'sessions#new'
  post "sign_in" => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
   root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
    
    validates :name, presence: true
    validates :email, presence: true, format: { with: /\A\S+@\S+\.\S+\z/, message: 'invalid format' }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.find_by(email: params[:session][:email])
        
        if @user
            if @user.authenticate(params[:session][:password])
                session[:user_id] = @user.id
                redirect_to root_path(id: @user.id), notice: 'Welcome Back!'
            else
               flash[:notice] = 'Invalid Email/Password' 
               render :new 
            end
        else
            flash[:notice] = 'User could not be found' 
               render :new
        end
    end
    
    def destroy
        session.delete(:user_id)
        redirect_to sign_in_path, notice: 'Successfully Signed Out'
        
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      #UserMailer.welcome_email(@user).deliver
      UserMailer.welcome_email(@user).deliver
      redirect_to user_path(id: @user.id), notice: "Successfully Signed Up"
    else

      render :new
      #redirent_to new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
     if @user.update_attributes(user_params)
       redirect_to user_path(id: @user.id), notice: "Successfully update"
     else
       flash[:notice]= "Update fail"
       render :edit
     end
     
  end

  def destroy
    @user = User.find(params[:id])
    
    if @user.destroy
    
      redirect_to users_path, notice: 'Successfully deleted User'
    else
      redirect_to request.referrer, "Cannot destroy user"
      render :index
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
        if !session[:user_id].blank?
        current_user = User.find(session[:user_id])
        else
        current_user = nil
        end
        
        return current_user
    end
    
    def current_user_logged_in?
        if current_user
         true
        else
         false
        end
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class = "navbar navbar-default">
    
    <div class='col-lg-8 col-md-4 col-xl-3'>
    <h1>time</h1>
    </div>
    <div class='col-lg-4 col-md-6 col-xl-9'>
   
    
        <ul class="nav nav-pills" role="tablist">
        
        <li role="presentation"<%= current_page?(root_path) ? "class=active" : ""%>> <%= link_to 'Home' , root_path %></li>
        <li role="presentation"<%= current_page?(controller: 'static_pages', action: 'about') ? "class=active" : ""%>> <%= link_to 'about' , about_path %></li>
        <li role="presentation"<%= current_page?(controller: 'static_pages', action: 'contact') ? "class=active" : ""%>> <%= link_to 'contact' , contact_path %></li>
         <li role="presentation"<%= current_page?(controller: 'users', action: 'index') ? "class=active" : ""%>> <%= link_to 'list' , users_path %></li>
       <%
         if current_user_logged_in?
             the_link = link_to 'sign out', sign_out_path, method: :delete
         else
             the_link = link_to 'sign in', sign_in_path
         end
       
       %>
        <li role="presentation"><%= the_link %></li>

        </ul>
    </div>
    
    
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div id="notice"><%= flash[:notice] %></div>
<div id="error"><%= flash[:error] %></div>
<div id="alert"><%= flash[:alert] %></div>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome</h1>
  
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
     
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
    
        <div class="input-group col-xs-6">
          <span class="input-group-addon"><%= f.label :name %></span>
          <%= f.text_field :name, class: "form-control" %>
        </div>        
    </div>
    <div class="row">
        <div class="input-group col-xs-6">
          <span class="input-group-addon"><%= f.label :email %></span>
          <%= f.text_field :email, class: "form-control" %>
        </div>        
    </div>
    <div class="row">
    
        <div class="input-group col-xs-6">
          <span class="input-group-addon"><%= f.label :password %></span>
          <%= f.password_field :password, class: "form-control" %>
        </div>        
    </div>
    <div class="row">
    
        <div class="input-group col-xs-6">
          <span class="input-group-addon"><%= f.label :password_confirmation %></span>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>        
    </div>
    <div class="form-group">
      <% if @user.new_record? %>
     
         <% submit_label = "Sign Up" %>
       <% else %>
         <% submit_label = "Update" %>
       <% end%>
      
      
    </div>
     
    <div class="row">
        <div class="input-group col-xs-6">
          <%= f.submit submit_label, class: "btn btn-default" %>
        </div>             
    </div>
<% end %>    

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>User list</h1>


<table>
    
    <tr>
        <th>Name</th>
        <th>Delete?</th>
        
        
    </tr>
    <% @users.each do |user| %>
    
    <tr>
       <td><%= user.name%></td> 
       <td> <%= link_to "Delete user" , user_path(user), method: :delete, confrim: "Are you sure?" %></td>
        
    </tr>
    
    
    <% end %>
    
</table>

app/views/users/new.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Register Now!</h1>
        <%= render 'form' %> 
    </div>
   
</div>

app/views/users/show.html.erb
<h1>User Profile</h1>


<h1><%= @user.name %></h1>
<h3>Details</h3>
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>